name: ams_dashboard
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cron: ^0.5.1
  dio: ^5.1.1
  easy_cron: ^0.9.2
  envied: ^0.3.0
  equatable: ^2.0.5
  file_picker: ^5.2.11
  flutter:
    sdk: flutter
  flutter_form_builder: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_slidable: ^3.0.0
  form_builder: ^1.0.1
  form_builder_validators: ^8.5.0
  freezed_annotation: ^2.2.0
  go_router: ^6.5.7
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  logger: ^1.3.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  riverpod: ^2.3.5
  riverpod_annotation: ^2.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.1.0
  sliding_up_panel: ^2.0.0+1
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  custom_lint: ^0.3.4
  envied_generator: ^0.3.0
  retrofit_generator: ^6.0.0+2
  riverpod_generator: ^2.2.1
  riverpod_lint: ^1.3.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
